<?php
//Custom Layouts
$layouts = array(
		'footer_11' => array(
				'name' => 'Footer Standard(*Tails)',
				'template' => '<p>[vc_row row_type=\"normal\" row_delimiter=\"1\" row_fixed=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1488469325500{background-color: #2c2a29 !important;}\"][vc_column icons_position=\"left\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\"][vc_row_inner][/vc_row_inner][vc_column_inner icons_position=\"left\"][/vc_column_inner][vc_empty_space alter_height=\"small\" hide_on_mobile=\"\"][vc_raw_html]JTVCaW5zdGFncmFtLWZlZWQlNUQ=[/vc_raw_html][vc_empty_space hide_on_mobile=\"\" css=\".vc_custom_1490019641956{padding-bottom: 0.5rem !important;}\"][vc_separator][/trx_sc_content][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\"][vc_row_inner css=\".vc_custom_1490256318215{padding-top: 0.4rem !important;}\"][vc_column_inner width=\"1/3\" icons_position=\"left\"][trx_widget_contacts googlemap=\"\" socials=\"1\" logo=\"356\" description=\"We offer a full array of medical services for dogs and cats. We provide best veterinarians, nurses, and staff.\"][/trx_widget_contacts][/vc_column_inner][vc_column_inner width=\"1/3\" icons_position=\"left\"][trx_widget_contacts googlemap=\"\" socials=\"\" title=\"Contacts\" address=\"NY, 106the Ave, Queens, USA\" phone=\"0 800-567-89-10\" email=\"info@veterinarytails.com\"][/trx_widget_contacts][/vc_column_inner][vc_column_inner width=\"1/3\" icons_position=\"left\"][vc_wp_text title=\"Stay in touch\"]Subscribe our newsletters!</p>
<p>[mc4wp_form id=\"470\"][/vc_wp_text][/vc_column_inner][vc_column_inner icons_position=\"left\"][vc_empty_space alter_height=\"small\" hide_on_mobile=\"\" css=\".vc_custom_1490024782828{margin-bottom: -0.9rem !important;}\"][/vc_column_inner][/vc_row_inner][/trx_sc_content][/vc_column][/vc_row][vc_row row_type=\"compact\" row_delimiter=\"\" row_fixed=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1488469345908{background-color: #393736 !important;}\"][vc_column icons_position=\"left\"][trx_sc_content size=\"1_1\" float=\"center\" number_position=\"br\" title_style=\"default\" css=\".vc_custom_1490024907230{margin-top: -0.7rem !important;margin-bottom: -0.7rem !important;}\"][vc_wp_text]<a href=\"https://themeforest.net/user/ancorathemes/portfolio\" target=\"_blank\" rel=\"noopener noreferrer\">AncoraThemes</a> &copy; {Y}. All rights reserved.[/vc_wp_text][/trx_sc_content][/vc_column][/vc_row]</p>
',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'footer'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1488469325500{background-color: #2c2a29 !important;}.vc_custom_1488469345908{background-color: #393736 !important;}.vc_custom_1490019641956{padding-bottom: 0.5rem !important;}.vc_custom_1490256318215{padding-top: 0.4rem !important;}.vc_custom_1490024782828{margin-bottom: -0.9rem !important;}.vc_custom_1490024907230{margin-top: -0.7rem !important;margin-bottom: -0.7rem !important;}'
						)
				),
		'header_19' => array(
				'name' => 'Header Fullwidth',
				'template' => '[vc_row row_type=\"compact\" row_delimiter=\"\" row_fixed=\"1\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1491211561548{padding-top: 1rem !important;padding-right: 6.7em !important;padding-bottom: 0.8rem !important;padding-left: 6.7em !important;}\"][vc_column width=\"1/6\" column_align=\"left\" icons_position=\"left\" column_type=\"center\"][trx_sc_layouts_logo][/vc_column][vc_column width=\"2/3\" column_align=\"center\" icons_position=\"left\" css=\".vc_custom_1490794175851{padding-top: 0.2rem !important;}\"][trx_sc_layouts_menu location=\"none\" menu=\"main-menu\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"1\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][/vc_column][vc_column width=\"1/6\" icons_position=\"left\" offset=\"vc_hidden-md vc_hidden-sm vc_hidden-xs\"][trx_sc_button type=\"default\" align=\"right\" icon_type=\"fontawesome\" icon_position=\"left\" link=\"/contacts\" title=\"contact us\"][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'header'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1491211561548{padding-top: 1rem !important;padding-right: 6.7em !important;padding-bottom: 0.8rem !important;padding-left: 6.7em !important;}.vc_custom_1490794175851{padding-top: 0.2rem !important;}'
						)
				),
		'header_20' => array(
				'name' => 'Header Fullwidth Simple',
				'template' => '[vc_row row_type=\"compact\" row_delimiter=\"1\" row_fixed=\"1\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1479713355363{padding-right: 2em !important;padding-left: 2em !important;}\"][vc_column width=\"1/4\" column_align=\"left\" column_type=\"center\"][trx_sc_layouts_logo type=\"default\" logo=\"\" logo_retina=\"\" id=\"\" class=\"\" css=\"\"][/vc_column][vc_column width=\"3/4\" column_align=\"right\"][trx_sc_layouts_menu type=\"default\" location=\"none\" menu=\"main-menu\" burger=\"\" mobile=\"1\" id=\"\" class=\"\" css=\"\" stretch=\"\" hover=\"slide_line\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"1\" mobile_menu=\"1\" mobile_hide=\"1\" hide_on_mobile=\"1\"][trx_sc_layouts_search type=\"default\" style=\"fullscreen\" ajax=\"\" hide_on_mobile=\"\" id=\"\" class=\"\" css=\"\"][trx_sc_layouts_cart type=\"default\" text=\"\" hide_on_mobile=\"\" id=\"\" class=\"\" css=\"\"][/vc_column][/vc_row][vc_row row_type=\"normal\" row_delimiter=\"\" row_fixed=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"1\" css=\".vc_custom_1479716553650{background-color: #f7f7f7 !important;}\"][vc_column column_align=\"center\"][trx_sc_content type=\"default\" size=\"1_1\" float=\"none\" align=\"none\" padding=\"none\" title_style=\"default\" title_align=\"default\" title=\"\" subtitle=\"\" description=\"\" link=\"\" link_text=\"\" link_image=\"\" scheme=\"inherit\" id=\"\" class=\"\" css=\"\"][trx_sc_layouts_title type=\"default\" icon_type=\"fontawesome\" icon_fontawesome=\"\" meta=\"1\" title=\"1\" breadcrumbs=\"1\" hide_on_mobile=\"\" id=\"\" class=\"\" css=\"\"][/trx_sc_content][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'header'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1479713355363{padding-right: 2em !important;padding-left: 2em !important;}.vc_custom_1479716553650{background-color: #f7f7f7 !important;}'
						)
				),
		'header_21' => array(
				'name' => 'Header Short /2 rows/',
				'template' => '[vc_row row_type=\"compact\" row_delimiter=\"\" row_fixed=\"\" hide_on_tablet=\"1\" hide_on_mobile=\"1\" hide_on_frontpage=\"\"][vc_column column_align=\"center\" icons_position=\"left\" column_type=\"center\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\" width=\"1_1\" width2=\"1_1\" css=\".vc_custom_1490091498734{margin-top: -0.45rem !important;border-bottom-width: 1px !important;padding-bottom: 0.3rem !important;border-bottom-color: #e5e5e5 !important;border-bottom-style: solid !important;}\"][vc_row_inner equal_height=\"yes\" content_placement=\"middle\"][vc_column_inner width=\"5/12\" column_align=\"left\" icons_position=\"left\"][vc_column_text]<strong><span style=\"color: #524d48;\">Call Us:</span> <span style=\"color: #c0bebd;\"><a href=\"tel:+08005552211\">0 800 555 22 11</a>, <a href=\"tel:+08001112233\">0 800 111 22 33</a></span></strong>[/vc_column_text][/vc_column_inner][vc_column_inner width=\"5/12\" icons_position=\"left\"][vc_column_text css=\".vc_custom_1490190150436{margin-right: -2.9rem !important;}\"]
<p style=\"text-align: right;\"><strong><span style=\"color: #524d48;\">Visit Us:</span>&nbsp;<span style=\"color: #c0bebd;\">9706 S. Somerset Court Naples, FL</span></strong></p>
[/vc_column_text][/vc_column_inner][vc_column_inner width=\"1/6\" column_align=\"right\" icons_position=\"left\"][trx_widget_contacts columns=\"\" googlemap=\"\" socials=\"1\" css=\".vc_custom_1490190103252{padding-right: 0.3rem !important;}\"][/trx_widget_contacts][/vc_column_inner][/vc_row_inner][/trx_sc_content][/vc_column][/vc_row][vc_row row_delimiter=\"\" row_fixed=\"1\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\"][vc_column icons_position=\"left\" column_type=\"center\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\" width=\"1_1\" width2=\"1_1\" css=\".vc_custom_1490092808571{padding-top: 0.7rem !important;padding-bottom: 1.3rem !important;}\"][vc_row_inner equal_height=\"yes\" content_placement=\"middle\"][vc_column_inner width=\"1/3\" column_align=\"left\" icons_position=\"left\"][trx_sc_layouts_logo][/vc_column_inner][vc_column_inner width=\"2/3\" column_align=\"right\" icons_position=\"left\"][trx_sc_layouts_menu location=\"none\" menu=\"main-menu\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"1\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][/vc_column_inner][/vc_row_inner][/trx_sc_content][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'header'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1490091498734{margin-top: -0.45rem !important;border-bottom-width: 1px !important;padding-bottom: 0.3rem !important;border-bottom-color: #e5e5e5 !important;border-bottom-style: solid !important;}.vc_custom_1490190150436{margin-right: -2.9rem !important;}.vc_custom_1490190103252{padding-right: 0.3rem !important;}.vc_custom_1490092808571{padding-top: 0.7rem !important;padding-bottom: 1.3rem !important;}'
						)
				),
		'header_481' => array(
				'name' => 'Header Tails',
				'template' => '<p>[vc_row row_type=\"compact\" row_delimiter=\"\" row_fixed=\"\" hide_on_tablet=\"1\" hide_on_mobile=\"1\" hide_on_frontpage=\"\"][vc_column column_align=\"center\" icons_position=\"left\" column_type=\"center\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\" width=\"1_1\" width2=\"1_1\" css=\".vc_custom_1490091498734{margin-top: -0.45rem !important;border-bottom-width: 1px !important;padding-bottom: 0.3rem !important;border-bottom-color: #e5e5e5 !important;border-bottom-style: solid !important;}\"][vc_row_inner equal_height=\"yes\" content_placement=\"middle\"][vc_column_inner width=\"5/12\" column_align=\"left\" icons_position=\"left\"][vc_column_text]<strong><span style=\"color: #524d48;\">Call Us:</span> <span style=\"color: #c0bebd;\"><a href=\"tel:08005552211\">0 800 555 22 11</a>, <a href=\"tel:08001112233\">0 800 111 22 33</a></span></strong>[/vc_column_text][/vc_column_inner][vc_column_inner width=\"5/12\" icons_position=\"left\"][vc_column_text css=\".vc_custom_1490190150436{margin-right: -2.9rem !important;}\"]</p>
<p style=\"text-align: right;\"><strong><span style=\"color: #524d48;\">Visit Us:</span>&nbsp;<span style=\"color: #c0bebd;\">9706 S. Somerset Court Naples, FL</span></strong></p>
<p>[/vc_column_text][/vc_column_inner][vc_column_inner width=\"1/6\" column_align=\"right\" icons_position=\"left\"][trx_widget_contacts columns=\"\" googlemap=\"\" socials=\"1\" css=\".vc_custom_1490190103252{padding-right: 0.3rem !important;}\"][/trx_widget_contacts][/vc_column_inner][/vc_row_inner][/trx_sc_content][/vc_column][/vc_row][vc_row row_delimiter=\"\" row_fixed=\"1\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\"][vc_column icons_position=\"left\" column_type=\"center\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\" width=\"1_1\" width2=\"1_1\" css=\".vc_custom_1490092808571{padding-top: 0.7rem !important;padding-bottom: 1.3rem !important;}\"][vc_row_inner equal_height=\"yes\" content_placement=\"middle\"][vc_column_inner width=\"1/3\" column_align=\"left\" icons_position=\"left\"][trx_sc_layouts_logo][/vc_column_inner][vc_column_inner width=\"2/3\" column_align=\"right\" icons_position=\"left\"][trx_sc_layouts_menu location=\"none\" menu=\"main-menu\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"1\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][/vc_column_inner][/vc_row_inner][/trx_sc_content][/vc_column][/vc_row][vc_row scheme=\"dark\" row_delimiter=\"\" row_fixed=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"1\" css=\".vc_custom_1564140324710{padding-top: 0.7rem !important;padding-bottom: 1rem !important;background: #f7f7f7 url(https://tails.ancorathemes.com/wp-content/uploads/2017/03/2-layers.png?id=485) !important;}\"][vc_column icons_position=\"left\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\"][trx_sc_layouts_title title=\"1\" meta=\"\" breadcrumbs=\"1\" icon_type=\"fontawesome\" icon_fontawesome=\"\"][/trx_sc_content][/vc_column][/vc_row]</p>
',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'header'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1564140324710{padding-top: 0.7rem !important;padding-bottom: 1rem !important;background: #f7f7f7 url(https://tails.ancorathemes.com/wp-content/uploads/2017/03/2-layers.png?id=485) !important;}.vc_custom_1490091498734{margin-top: -0.45rem !important;border-bottom-width: 1px !important;padding-bottom: 0.3rem !important;border-bottom-color: #e5e5e5 !important;border-bottom-style: solid !important;}.vc_custom_1490190150436{margin-right: -2.9rem !important;}.vc_custom_1490190103252{padding-right: 0.3rem !important;}.vc_custom_1490092808571{padding-top: 0.7rem !important;padding-bottom: 1.3rem !important;}'
						)
				)
		);
?>